# Generated by Django 4.0.2 on 2022-04-26 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reistration',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrationdesignation', to='app.designation'),
        ),
    ]
