# Generated by Django 4.0.2 on 2022-04-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reistration_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='addrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('Date_Time', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('req_details', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('completion_date', models.CharField(max_length=255)),
                ('urgency', models.CharField(max_length=255)),
            ],
        ),
    ]
