# Generated by Django 4.0.2 on 2022-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='givework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work', models.CharField(max_length=255)),
                ('startdate', models.DateField(max_length=255)),
                ('enddate', models.DateField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
