# Generated by Django 4.0.2 on 2022-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_addvendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('accountno', models.CharField(max_length=255)),
                ('paymethod', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
    ]
