# Generated by Django 4.0.2 on 2022-04-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givework',
            name='name',
        ),
        migrations.AddField(
            model_name='givework',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.reistration'),
        ),
    ]
