# Generated by Django 4.0.2 on 2022-04-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_register_remove_givework_user_delete_reistration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='givework',
            old_name='firstname',
            new_name='user',
        ),
    ]
