# Generated by Django 4.0.2 on 2022-04-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_firstname_givework_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
            ],
        ),
    ]
