# Generated by Django 4.0.2 on 2022-04-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_stockdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='workstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
