# Generated by Django 4.0.2 on 2022-04-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.register'),
        ),
    ]
