# Generated by Django 4.0.2 on 2022-04-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactus',
        ),
    ]
