# Generated by Django 4.0.2 on 2022-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_repairing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='replay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
